version: "3.8"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    user: ${PUID}
    environment:
      - GF_LOG_LEVEL=${GF_LOG_LEVEL}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
    ports:
      - ${PORT}:3000
    volumes:
      - ./volumes/config:/etc/grafana
      - ./volumes/data:/var/lib/grafana
      - ./volumes/log:/var/log/grafana
